security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api_unsecured:
            pattern: ^/api/(doc|login|category/list|product/list)
            stateless: true
            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        - {path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/category/list, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/product/list, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api, roles: IS_AUTHENTICATED_FULLY}
        - {path: ^/user/profile, roles: ROLE_USER}
        - {path: ^/basket, roles: ROLE_USER}
        - {path: ^/submit/order, roles: ROLE_USER}
