version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - .:/app:cached
    environment:
      CONTAINER_APP_NAME: app

  app:
    build: ./docker/php
    environment:
      PHP_IDE_CONFIG: "serverName=shop-app"
    volumes:
      - .:/app:cached
      - ./docker/php/overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini